version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Persist data
      - ./data:/app/data
      # Mount media directories
      - ./static/music:/app/static/music
      - ./static/boxart:/app/static/boxart
      - ./static/consoles:/app/static/consoles
      - ./static/uploads:/app/static/uploads
      - ./static/library:/app/static/library
    environment:
      - FLASK_ENV=production
      - FLASK_APP=shed.py
    restart: always

volumes:
  data:
  music:
  boxart:
  consoles:
  uploads:
  library: