
# docker-compose.dev.yml
version: '3.8'
services:
  web:
    build: .
    ports:
      - "5045:5045"
    volumes:
      - .:/app
      - /app/venv
    environment:
      - FLASK_APP=shed.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PORT=5045
    command: flask run --host=0.0.0.0 --port=5045